### ISSUE TITLE
osqp 0.6.0 breaks miosqp

### ISSUE THREAD

**Issue by blake-riley** [oxfordcontrol/miosqp#6]
Hi,
The code in `run_examples.py` does not work.
If I `pip install "osqp<0.6"` (which installs `osqp==0.5.0`), the code from `run_examples.py` is able to successfully run.
I gather that there has been a change in the way constants are exported from `osqp-python`?

Here is a traceback:
```
Traceback (most recent call last):
  File "run_examples.py", line 12, in <module>
    random_miqp.run_example()
  File "/tmp/miosqp/examples/random_miqp/run_example.py", line 196, in run_example
    density_level, random_seed, solver='miosqp')
  File "/tmp/miosqp/examples/random_miqp/run_example.py", line 121, in solve
    osqp_settings)
  File "/tmp/miosqp/miosqp/solver.py", line 59, in setup
    self.work = Workspace(data, settings, qp_settings)
  File "/tmp/miosqp/miosqp/workspace.py", line 80, in __init__
    root = Node(self.data, self.data.l, self.data.u, self.solver)
  File "/tmp/miosqp/miosqp/node.py", line 87, in __init__
    self.status = self.solver.constant('OSQP_UNSOLVED')
AttributeError: 'OSQP' object has no attribute 'constant'
```

**Comment by bstellato** [comment]
Thanks for pointing this out. This is fixed on master.
